spring.application.name=knp_backend

logging.level.root=INFO
logging.level.kr.go.knp_system=INFO

# ===============================
# 서버포트
# ===============================
server.port=8080

# ===============================
# LDAP 서버 기본 설정
# ===============================
# spring.ldap.urls=ldap://localhost:8389
# spring.ldap.base=dc=springframework,dc=org
# spring.ldap.username=cn=admin, dc=springframework,dc=org
# spring.ldap.password=123

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.ldap=DEBUG

# ===============================
# MariaDB Database Configuration
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3306/knp_system
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


# 자동 재시작
# true > 코드 수정 후 저장하면 애플리케이션 재시작
# DevTools 자동 재시작 활성화
#spring.devtools.restart.enabled=true

# LDAP 설정파일
#spring.ldap.urls=ldap://localhost:8390
#spring.ldap.embedded.enabled=false
# spring.ldap.embedded.ldif=classpath:test-server.ldif
# spring.ldap.embedded.base-dn=dc=springframework,dc=org
# spring.ldap.embedded.port=8390

# ────── Swagger UI (SpringDoc) ──────
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.default-produces-media-type=application/json

spring.mvc.pathmatch.matching-strategy=ant-path-matcher

spring.jwt.secret=change-this-to-a-long-random-string-at-least-32-bytes
app.jwt.expiration-ms=3600000

# Spring Security 세션 정책 관련 (필요 시)
spring.security.filter.order=0